# Generated by Django 3.2.4 on 2021-06-08 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210608_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_drawing',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.TextField(default='bitch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='text',
            field=models.TextField(default='Hello World'),
        ),
    ]
